apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    image: quay.io/rafiu007/clair:quaypj
    imagePullSecretName: redhat-pull-secret
    deploymentStrategy: Recreate
    externalAccess:
      tls:
        termination: passthrough
    skipSetup: false
    keepConfigDeployment: true
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret