---
log_level: debug-color
introspection_addr: ":8089"
http_listen_addr: ":8080"
indexer:
  connstring: host=clairv4-postgres port=5432 user=clair dbname=clair password=abc sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  indexer_addr: http://clair-indexer:8080/
  connstring: host=clairv4-postgres port=5432 user=clair dbname=clair password=abc sslmode=disable
  max_conn_pool: 100
  migrations: true
notifier:
  indexer_addr: http://clair-indexer:8080/
  matcher_addr: http://clair-indexer:8080/
  connstring: host=clairv4-postgres port=5432 user=clair dbname=clair password=abc sslmode=disable
  migrations: true
  delivery_interval: 5000000s
  poll_interval: 100005s
  # webhook:
  #   target: "http://webhook/"
  #   callback: "http://clair-notifier/notifier/api/v1/notifications"
  amqp:
    direct: true
    exchange:
      name: ""
      type: "direct"
      durable: true
      auto_delete: false
    uris: ["amqp://guest:guest@clair-rabbitmq:5672/"]
    routing_key: "notifications"
    callback: "http://clair-notifier/notifier/api/v1/notifications"
# tracing and metrics config
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent:
      endpoint: "jaeger:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
