apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    image: quay.io/rafiu007/clair:quaypj
    imagePullSecretName: redhat-pull-secret
    deploymentStrategy: Recreate
    enableRepoMirroring: true
    externalAccess:
      tls:
        termination: edge
    skipSetup: false
    keepConfigDeployment: true
    # registryBackends:
    #   - name: s3
    #     s3:
    #       accessKey: minio
    #       secretkey: minio123
    #       host: minio-service

  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
