apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: appvuln
        image: quayecosystem-quay-quay-enterprise.apps.arajkuma-osa.devcluster.openshift.com/clairv4/pyvuln:latest
        command: ["sleep", "123456"]
      nodeSelector:
        beta.kubernetes.io/os: linux